[project]
name = "send-mail"
version = "0.1.0"
description = "Script to send CV emails"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    "E",
    "EM",
    "W",
    "F",
    "I",
    "N",
    "UP",
    "B",
    "A",
    "YTT",
    "ASYNC",
    "S",
    "BLE",
    "C4",
    "PIE",
    "SIM",
    "RET",
    "ARG",
    "PTH",
    "ERA",
    "PL",
    "RUF",
    "PT",
    "ANN",
    "D101",
    "D102",
    "D103",
]
ignore = [
    "E501",
    "ISC001",
    "COM812",
    "D203",
    "D213",
    "ANN201",
    "ANN204",
    "ERA001",
    "PLR0913",
    "PLR0912",
    "PLR0915",
    "PLR0911",
    "PLR2004",
    "PLW2901",
    "PLC0414",
    "RET504",
    "ARG002",
    "SIM108",
    "A003",
]

[tool.pyright]
include = ["send_cv_mail.py"]
typeCheckingMode = "strict"

# Environment
pythonVersion = "3.14"
deprecateTypingAliases = true

# Rules that default to "none" in strict mode
reportCallInDefaultInitializer = "error"
reportImplicitOverride = "error"
reportImportCycles = "error"
reportMissingSuperCall = "error"
reportPropertyTypeMismatch = "error"
reportUninitializedInstanceVariable = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportUnreachable = "error"